In [31]:
import joblib
import os
import streamlit as st
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import pandas as pd
import numpy as np

In [3]:
# Load the model
model = joblib.load('habitaclia_final_model.sav')

In [7]:
import pandas as pd

# Define the options for each column
room_options = list(range(1, 11))
bathroom_options = list(range(1, 11))
size_options = list(range(1, 1001))
neighborhood_options = ['Baró de Viver', 'Can Baró', 'Can Peguera', 'Canyelles', 'Ciutat Meridiana', 'Diagonal Mar i el Front Marítim del Poblenou', 'Horta', 'Hostafrancs', 'Montbau', 'Navas', 'Pedralbes', 'Porta', 'Provençals del Poblenou', 'Sant Andreu', 'Sant Antoni', 'Sant Genís dels Agudells', 'Sant Gervasi - la Bonanova', 'Sant Martí de Provençals', 'Sant Pere, Santa Caterina i la Ribera', 'Sants', 'Sants - Badal', 'Sarrià', 'Torre Baró', 'Vallbona', 'Vallcarca i els Penitents', 'Vallvidrera, el Tibidabo i les Planes', 'Verdun', 'Vilapicina i la Torre Llobeta', 'el Baix Guinardó', 'el Barri Gòtic', 'el Besòs i el Maresme', 'el Bon Pastor', "el Camp d'en Grassot i Gràcia Nova", "el Camp de l'Arpa del Clot", 'el Carmel', 'el Clot', 'el Coll', 'el Congrés i els Indians', 'el Fort Pienc', 'el Guinardó', 'el Parc i la Llacuna del Poblenou', 'el Poble-sec', 'el Poblenou', 'el Putxet i el Farró', 'el Raval', 'el Turó de la Peira', "l'Antiga Esquerra de l'Eixample", 'la Barceloneta', 'la Bordeta', 'la Clota', "la Dreta de l'Eixample", "la Font d'en Fargues", 'la Font de la Guatlla', 'la Guineueta', 'la Marina de Port', 'la Marina del Prat Vermell', 'la Maternitat i Sant Ramon', "la Nova Esquerra de l'Eixample", "la Prosperitat", 'la Sagrada Família', 'la Sagrera', 'la Salut', 'la Teixonera', 'la Trinitat Nova', 'la Trinitat Vella', "la Vall d'Hebron", 'la Verneda i la Pau', 'la Vila Olímpica del Poblenou', 'la Vila de Gràcia', 'les Corts', 'les Roquetes', 'les Tres Torres']
property_type_options = ['APARTMENT', 'DUPLEX', 'FLAT', 'GROUND_FLOOR', 'HOUSE', 'LOFT', 'PAIRED_HOUSE', 'PENTHOUSE', 'SINGLE_FAMILY_SEMI_DETACHED', 'STUDIO', 'TRIPLEX']

# Create an empty list to store user inputs
data = []

# Prompt the user for inputs and validate them
while True:
    rooms = input("Enter the number of rooms (1-10): ")
    if rooms.isdigit() and int(rooms) in room_options:
        break
    print("Invalid input! Please enter a number between 1 and 10.")

while True:
    bathrooms = input("Enter the number of bathrooms (1-10): ")
    if bathrooms.isdigit() and int(bathrooms) in bathroom_options:
        break
    print("Invalid input! Please enter a number between 1 and 10.")

while True:
    size_m2 = input("Enter the size in square meters (1-1000): ")
    if size_m2.isdigit() and int(size_m2) in size_options:
        break
    print("Invalid input! Please enter a number between 1 and 1000.")

while True:
    print("Select a neighborhood from the options:")
    for i, neighborhood in enumerate(neighborhood_options, start=1):
        print(f"{i}. {neighborhood}")
    neighborhood_choice = input("Enter the number corresponding to the neighborhood: ")
    if neighborhood_choice.isdigit() and int(neighborhood_choice) in range(1, len(neighborhood_options) + 1):
        neighborhood = neighborhood_options[int(neighborhood_choice) - 1]
        break
    print("Invalid input! Please enter a valid number.")

while True:
    print("Select a property type from the options:")
    for i, prop_type in enumerate(property_type_options, start=1):
        print(f"{i}. {prop_type}")
    property_type_choice = input("Enter the number corresponding to the property type: ")
    if property_type_choice.isdigit() and int(property_type_choice) in range(1, len(property_type_options) + 1):
        property_type = property_type_options[int(property_type_choice) - 1]
        break
    print("Invalid input! Please enter a valid number.")

# Append the user inputs as a new dictionary to the list
data.append({'rooms': int(rooms), 'bathrooms': int(bathrooms), 'size_m2': int(size_m2), 'neighborhood': neighborhood, 'property_type': property_type})

# Create the DataFrame from the list of dictionaries
df = pd.DataFrame(data)

# Display the dataframe
print(df)

Enter the number of rooms (1-10): 3
Enter the number of bathrooms (1-10): 2
Enter the size in square meters (1-1000): 90
Select a neighborhood from the options:
1. Baró de Viver
2. Can Baró
3. Can Peguera
4. Canyelles
5. Ciutat Meridiana
6. Diagonal Mar i el Front Marítim del Poblenou
7. Horta
8. Hostafrancs
9. Montbau
10. Navas
11. Pedralbes
12. Porta
13. Provençals del Poblenou
14. Sant Andreu
15. Sant Antoni
16. Sant Genís dels Agudells
17. Sant Gervasi - la Bonanova
18. Sant Martí de Provençals
19. Sant Pere, Santa Caterina i la Ribera
20. Sants
21. Sants - Badal
22. Sarrià
23. Torre Baró
24. Vallbona
25. Vallcarca i els Penitents
26. Vallvidrera, el Tibidabo i les Planes
27. Verdun
28. Vilapicina i la Torre Llobeta
29. el Baix Guinardó
30. el Barri Gòtic
31. el Besòs i el Maresme
32. el Bon Pastor
33. el Camp d'en Grassot i Gràcia Nova
34. el Camp de l'Arpa del Clot
35. el Carmel
36. el Clot
37. el Coll
38. el Congrés i els Indians
39. el Fort Pienc
40. el Guinardó
41. el Parc i la Llacuna del Poblenou
42. el Poble-sec
43. el Poblenou
44. el Putxet i el Farró
45. el Raval
46. el Turó de la Peira
47. l'Antiga Esquerra de l'Eixample
48. la Barceloneta
49. la Bordeta
50. la Clota
51. la Dreta de l'Eixample
52. la Font d'en Fargues
53. la Font de la Guatlla
54. la Guineueta
55. la Marina de Port
56. la Marina del Prat Vermell
57. la Maternitat i Sant Ramon
58. la Nova Esquerra de l'Eixample
59. la Prosperitat
60. la Sagrada Família
61. la Sagrera
62. la Salut
63. la Teixonera
64. la Trinitat Nova
65. la Trinitat Vella
66. la Vall d'Hebron
67. la Verneda i la Pau
68. la Vila Olímpica del Poblenou
69. la Vila de Gràcia
70. les Corts
71. les Roquetes
72. les Tres Torres
Enter the number corresponding to the neighborhood: 36
Select a property type from the options:
1. APARTMENT
2. DUPLEX
3. FLAT
4. GROUND_FLOOR
5. HOUSE
6. LOFT
7. PAIRED_HOUSE
8. PENTHOUSE
9. SINGLE_FAMILY_SEMI_DETACHED
10. STUDIO
11. TRIPLEX
Enter the number corresponding to the property type: 3
   rooms  bathrooms  size_m2 neighborhood property_type
0      3          2       90      el Clot          FLAT

In [8]:
df

   rooms  bathrooms  size_m2 neighborhood property_type
0      3          2       90      el Clot          FLAT

In [28]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# Define the options for each column
room_options = list(range(1, 11))
bathroom_options = list(range(1, 11))
size_options = list(range(1, 1001))
neighborhood_options = ['Baró de Viver', 'Can Baró', 'Can Peguera', 'Canyelles', 'Ciutat Meridiana', 'Diagonal Mar i el Front Marítim del Poblenou', 'Horta', 'Hostafrancs', 'Montbau', 'Navas', 'Pedralbes', 'Porta', 'Provençals del Poblenou', 'Sant Andreu', 'Sant Antoni', 'Sant Genís dels Agudells', 'Sant Gervasi - la Bonanova', 'Sant Martí de Provençals', 'Sant Pere, Santa Caterina i la Ribera', 'Sants', 'Sants - Badal', 'Sarrià', 'Torre Baró', 'Vallbona', 'Vallcarca i els Penitents', 'Vallvidrera, el Tibidabo i les Planes', 'Verdun', 'Vilapicina i la Torre Llobeta', 'el Baix Guinardó', 'el Barri Gòtic', 'el Besòs i el Maresme', 'el Bon Pastor', "el Camp d'en Grassot i Gràcia Nova", "el Camp de l'Arpa del Clot", 'el Carmel', 'el Clot', 'el Coll', 'el Congrés i els Indians', 'el Fort Pienc', 'el Guinardó', 'el Parc i la Llacuna del Poblenou', 'el Poble-sec', 'el Poblenou', 'el Putxet i el Farró', 'el Raval', 'el Turó de la Peira', "l'Antiga Esquerra de l'Eixample", 'la Barceloneta', 'la Bordeta', 'la Clota', "la Dreta de l'Eixample", "la Font d'en Fargues", 'la Font de la Guatlla', 'la Guineueta', 'la Marina de Port', 'la Marina del Prat Vermell', 'la Maternitat i Sant Ramon', "la Nova Esquerra de l'Eixample", "la Prosperitat", 'la Sagrada Família', 'la Sagrera', 'la Salut', 'la Teixonera', 'la Trinitat Nova', 'la Trinitat Vella', "la Vall d'Hebron", 'la Verneda i la Pau', 'la Vila Olímpica del Poblenou', 'la Vila de Gràcia', 'les Corts', 'les Roquetes', 'les Tres Torres']
property_type_options = ['APARTMENT', 'DUPLEX', 'FLAT', 'GROUND_FLOOR', 'HOUSE', 'LOFT', 'PAIRED_HOUSE', 'PENTHOUSE', 'SINGLE_FAMILY_SEMI_DETACHED', 'STUDIO', 'TRIPLEX']

# Create an empty list to store user inputs
data = []

# Prompt the user for inputs and validate them
while True:
    rooms = input("Enter the number of rooms (1-10): ")
    if rooms.isdigit() and int(rooms) in room_options:
        break
    print("Invalid input! Please enter a number between 1 and 10.")

while True:
    bathrooms = input("Enter the number of bathrooms (1-10): ")
    if bathrooms.isdigit() and int(bathrooms) in bathroom_options:
        break
    print("Invalid input! Please enter a number between 1 and 10.")

while True:
    size_m2 = input("Enter the size in square meters (1-1000): ")
    if size_m2.isdigit() and int(size_m2) in size_options:
        break
    print("Invalid input! Please enter a number between 1 and 1000.")

while True:
    print("Select a neighborhood from the options:")
    for i, neighborhood in enumerate(neighborhood_options, start=1):
        print(f"{i}. {neighborhood}")
    neighborhood_choice = input("Enter the number corresponding to the neighborhood: ")
    if neighborhood_choice.isdigit() and int(neighborhood_choice) in range(1, len(neighborhood_options) + 1):
        neighborhood = neighborhood_options[int(neighborhood_choice) - 1]
        break
    print("Invalid input! Please enter a valid number.")

while True:
    print("Select a property type from the options:")
    for i, prop_type in enumerate(property_type_options, start=1):
        print(f"{i}. {prop_type}")
    property_type_choice = input("Enter the number corresponding to the property type: ")
    if property_type_choice.isdigit() and int(property_type_choice) in range(1, len(property_type_options) + 1):
        property_type = property_type_options[int(property_type_choice) - 1]
        break
    print("Invalid input! Please enter a valid number.")

# Append the user inputs as a new dictionary to the list
data.append({'Rooms': int(rooms), 'Bathrooms': int(bathrooms), 'Size_m2': int(size_m2), 'Property_type': property_type, 'nom_barri': neighborhood})

# Create the DataFrame from the list of dictionaries
df = pd.DataFrame(data)

Enter the number of rooms (1-10): 3
Enter the number of bathrooms (1-10): 2
Enter the size in square meters (1-1000): 90
Select a neighborhood from the options:
1. Baró de Viver
2. Can Baró
3. Can Peguera
4. Canyelles
5. Ciutat Meridiana
6. Diagonal Mar i el Front Marítim del Poblenou
7. Horta
8. Hostafrancs
9. Montbau
10. Navas
11. Pedralbes
12. Porta
13. Provençals del Poblenou
14. Sant Andreu
15. Sant Antoni
16. Sant Genís dels Agudells
17. Sant Gervasi - la Bonanova
18. Sant Martí de Provençals
19. Sant Pere, Santa Caterina i la Ribera
20. Sants
21. Sants - Badal
22. Sarrià
23. Torre Baró
24. Vallbona
25. Vallcarca i els Penitents
26. Vallvidrera, el Tibidabo i les Planes
27. Verdun
28. Vilapicina i la Torre Llobeta
29. el Baix Guinardó
30. el Barri Gòtic
31. el Besòs i el Maresme
32. el Bon Pastor
33. el Camp d'en Grassot i Gràcia Nova
34. el Camp de l'Arpa del Clot
35. el Carmel
36. el Clot
37. el Coll
38. el Congrés i els Indians
39. el Fort Pienc
40. el Guinardó
41. el Parc i la Llacuna del Poblenou
42. el Poble-sec
43. el Poblenou
44. el Putxet i el Farró
45. el Raval
46. el Turó de la Peira
47. l'Antiga Esquerra de l'Eixample
48. la Barceloneta
49. la Bordeta
50. la Clota
51. la Dreta de l'Eixample
52. la Font d'en Fargues
53. la Font de la Guatlla
54. la Guineueta
55. la Marina de Port
56. la Marina del Prat Vermell
57. la Maternitat i Sant Ramon
58. la Nova Esquerra de l'Eixample
59. la Prosperitat
60. la Sagrada Família
61. la Sagrera
62. la Salut
63. la Teixonera
64. la Trinitat Nova
65. la Trinitat Vella
66. la Vall d'Hebron
67. la Verneda i la Pau
68. la Vila Olímpica del Poblenou
69. la Vila de Gràcia
70. les Corts
71. les Roquetes
72. les Tres Torres
Enter the number corresponding to the neighborhood: 36
Select a property type from the options:
1. APARTMENT
2. DUPLEX
3. FLAT
4. GROUND_FLOOR
5. HOUSE
6. LOFT
7. PAIRED_HOUSE
8. PENTHOUSE
9. SINGLE_FAMILY_SEMI_DETACHED
10. STUDIO
11. TRIPLEX
Enter the number corresponding to the property type: 3

In [38]:
# Pass the encoded data to the machine learning model
predictions = model.predict(df_new)

# Display the predictions
print(round(predictions[0],2))

4163.33

In [29]:
df

   Rooms  Bathrooms  Size_m2 Property_type nom_barri
0      3          2       90          FLAT   el Clot

In [16]:
neighborhood_dummies

   el Clot
0     True

In [25]:
df_hab = pd.read_csv(f'../data/final_data/habitaclia_bcn_all_data_combined_20230623_with_districts.csv', encoding='utf-8-sig')

In [26]:
df_hab.drop(columns=['ID', 'Address', 'City', 'Neightbourhood', 'Links', 'Description','Date_Scraped', 'District', 'Price_€', 'Price_m2'], inplace=True)

In [27]:
df_hab

       Rooms  Bathrooms  Size_m2 Property_type                   nom_barri
0          5          1      195          FLAT      la Dreta de l'Eixample
1          4          2      176          FLAT        el Putxet i el Farró
2          3          2      135          FLAT          la Sagrada Família
3          3          2      117          FLAT                 Sant Antoni
4          5          3      263          FLAT  Sant Gervasi - la Bonanova
...      ...        ...      ...           ...                         ...
15180      2          1       53          FLAT                     Montbau
15181      2          1       86          FLAT            el Baix Guinardó
15182      3          2       90          FLAT           la Marina de Port
15183      3          2      101        DUPLEX           la Trinitat Vella
15184      1          1       75          FLAT                    el Raval

[15185 rows x 5 columns]

In [34]:
df_new = pd.concat([df_hab, df], ignore_index=True)
df_new

       Rooms  Bathrooms  Size_m2 Property_type                   nom_barri
0          5          1      195          FLAT      la Dreta de l'Eixample
1          4          2      176          FLAT        el Putxet i el Farró
2          3          2      135          FLAT          la Sagrada Família
3          3          2      117          FLAT                 Sant Antoni
4          5          3      263          FLAT  Sant Gervasi - la Bonanova
...      ...        ...      ...           ...                         ...
15181      2          1       86          FLAT            el Baix Guinardó
15182      3          2       90          FLAT           la Marina de Port
15183      3          2      101        DUPLEX           la Trinitat Vella
15184      1          1       75          FLAT                    el Raval
15185      3          2       90          FLAT                     el Clot

[15186 rows x 5 columns]

In [35]:
df_new = pd.get_dummies(df_new, columns=['nom_barri', 'Property_type'], dtype="int")
df_new["Rooms"] = scaler.fit_transform(df_new["Rooms"].values.reshape(-1, 1))
df_new["Bathrooms"] = scaler.fit_transform(df_new["Bathrooms"].values.reshape(-1, 1))
df_new["Size_m2"] = min_max_scaler.fit_transform(df_new["Size_m2"].values.reshape(-1, 1))
df_new = df_new.tail(1)
df_new

,Rooms,Bathrooms,Size_m2,nom_barri_Baró de Viver,nom_barri_Can Baró,nom_barri_Can Peguera,nom_barri_Canyelles,nom_barri_Ciutat Meridiana,nom_barri_Diagonal Mar i el Front Marítim del Poblenou,nom_barri_Horta,...,Property_type_DUPLEX,Property_type_FLAT,Property_type_GROUND_FLOOR,Property_type_HOUSE,Property_type_LOFT,Property_type_PAIRED_HOUSE,Property_type_PENTHOUSE,Property_type_SINGLE_FAMILY_SEMI_DETACHED,Property_type_STUDIO,Property_type_TRIPLEX
15185,-0.039189,0.271855,0.05566,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0